config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  resources :teachers
  resources :groups
  resources :classrooms
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher, optional: true

  validates :number, presence: true
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classrooms = Classroom.all

    api_classrooms = []
    @classrooms.each do |classroom|
      api_classrooms.push({id: classroom.id, number: classroom.number, teacher: "#{classroom&.teacher&.name} #{classroom&.teacher&.surname}", teacher_id: classroom&.teacher&.id})
    end

    respond_to do |format|
      format.html
      format.json { render json: api_classrooms }
    end
  end

  def new
    @selection = Teacher.all.collect { |t| [t.name, t.id] }
  end

  def create
    parameters = params[:classroom]
    classroom = Classroom.create(number: parameters[:number])
    unless parameters[:teacher_id].blank?
      teacher = Teacher.find(parameters[:teacher_id])

      if teacher.classroom.blank?
        classroom.update(teacher: teacher)
      else
        teacher.classroom.update(teacher: nil)
        classroom.update(teacher: teacher)
      end
    end

    if classroom.errors.blank?
      respond_to do |format|
        format.html { redirect_to classrooms_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = classroom.errors
      respond_to do |format|
        format.html { redirect_to new_classroom_path }
        format.json { render json: {errors: classroom.errors} }
      end
    end
  end

  def edit
    @classroom = Classroom.find(params[:id])
    @selection = Teacher.all.collect {|p| [ p.name, p.id ] }
  end

  def update
    parameters = params[:classroom]
    classroom = Classroom.find(params[:id])
    classroom.update(number: parameters[:number])

    if !parameters[:teacher_id].blank?
      teacher = Teacher.find(parameters[:teacher_id].to_i)

      if teacher.classroom.blank?
        classroom.update(teacher: teacher)
      else
        teacher.classroom.update(teacher: nil)
        classroom.update(teacher: teacher)
      end
    else
      classroom.update(teacher: nil)
    end

    if classroom.errors.blank?
      respond_to do |format|
        format.html { redirect_to classrooms_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = classroom.errors
      respond_to do |format|
        format.html { redirect_to new_classroom_path }
        format.json { render json: {errors: classroom.errors} }
      end
    end
  end

  def destroy
    classroom = Classroom.find(params[:id])
    classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_path }
      format.json { render json: {success: true} }
    end
  end
end

app/views/classrooms/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Edit classroom</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>


  <%= form_with(model: @classroom, local: true) do |form| %>
    <p>
      <%= form.label 'Number' %><br>
      <%= form.text_field :number %>
    </p>

    <p>
      <%= form.label 'Teacher' %><br>
      <%= form.select :teacher_id, @selection, { include_blank: true }, :value => @classroom&.teacher&.name %>
    </p>

    <p>
      <%= form.submit 'Change' %>
    </p>
  <% end %>
</div>

app/views/classrooms/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<%= link_to 'Add classroom', new_classroom_path %>


<div class="container">
  <table class="table table-borderless bg-light">
    <thead>
      <tr class="table-primary">
        <th scope="col">name</th>
        <th scope="col">teacher</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @classrooms.each do |classroom| %>
        <tr>
          <td><%= classroom.number %></td>
          <td><%= classroom&.teacher&.name %> <%= classroom&.teacher&.surname %></td>
          <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
          <td><%= link_to 'Remove', classroom_path(classroom),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/classrooms/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Add new classroom</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>

  <%= form_with scope: :classroom, url: classrooms_path, local: true do |form| %>
    <p>
      <%= form.label 'Number' %><br>
      <%= form.text_field :number %>
    </p>
    <p>
      <%= form.label 'Teacher' %><br>
      <%= form.select :teacher_id, @selection, { include_blank: true } %>
    </p>
    <p>
      <%= form.submit 'Add' %>
    </p>
  <% end %>
</div>