config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  resources :teachers
  resources :groups
  resources :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group

  validates :name, presence: true
  validates :surname, presence: true
  validates :group_id, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all

    api_students = []
    @students.each do |student|
      api_students.push({id: student.id, name: student&.name, surname: student&.surname, group: student&.group&.name})
    end

    respond_to do |format|
      format.html
      format.json { render json: api_students }
     end
  end

  def create
    parameters = params[:student]

    student = Student.create(surname: parameters[:surname],
                        name: parameters[:name])
    group = Group.find_by(name: parameters[:group_name])
    unless group.blank?
      student.update(group: group)
    end

    if student.errors.blank?
      respond_to do |format|
        format.html { redirect_to students_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = student.errors
      respond_to do |format|
        format.html { redirect_to new_student_path }
        format.json { render json: {errors: student.errors} }
      end
    end
  end

  def new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def show
  end

  def update
    parameters = params[:student]
    student = Student.find(params[:id])

    student.update(surname: parameters[:surname],
                        name: parameters[:name])
    group = Group.find_by(name: parameters[:group_name])
    unless group.blank?
      student.update(group: group)
    end

    if student.errors.blank?
      respond_to do |format|
        format.html { redirect_to students_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = student.errors
      respond_to do |format|
        format.html { redirect_to edit_student_path }
        format.json { render json: {errors: student.errors} }
      end
    end
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy

    respond_to do |format|
      format.html { redirect_to students_path }
      format.json { render json: {success: true} }
    end
  end
end

app/views/students/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Edit student</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>


  <%= form_with(model: @student, local: true) do |form| %>
    <p>
      <%= form.label 'Name' %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label 'Surname' %><br>
      <%= form.text_field :surname %>
    </p>

    <p>
      <%= form.label 'Group' %><br>
      <%= form.text_field :group_name, :value => @student&.group&.name %>
    </p>

    <p>
      <%= form.submit 'Change' %>
    </p>
  <% end %>
</div>

app/views/students/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<%= link_to 'Add student', new_student_path %>


<div class="container">
  <table class="table table-borderless bg-light">
    <thead>
      <tr class="table-primary">
        <th scope="col">name</th>
        <th scope="col">surname</th>
        <th scope="col">group</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.surname %></td>
          <td><%= student&.group&.name %></td>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
          <td><%= link_to 'Suspend', student_path(student),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Add new student</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>

  <%= form_with scope: :student, url: students_path, local: true do |form| %>
    <p>
      <%= form.label 'Name' %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label 'Surname' %><br>
      <%= form.text_field :surname %>
    </p>

    <p>
      <%= form.label 'Group' %><br>
      <%= form.text_field :group_name %>
    </p>

    <p>
      <%= form.submit 'Add' %>
    </p>
  <% end %>
</div>