config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  resources :teachers
  resources :groups
  resources :classrooms
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :students
  belongs_to :teacher, optional: true

  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all

    api_groups = []
    @groups.each do |group|
      api_groups.push({id: group.id, name: group.name, teacher: "#{group&.teacher&.name} #{group&.teacher&.surname}", teacher_id: group&.teacher_id})
    end

    respond_to do |format|
      format.html
      format.json { render json: api_groups }
    end
  end

  def new
    @selection = Teacher.all.collect {|p| [ p.name, p.id ] }
  end

  def create
    parameters = params[:group]
    group = Group.create(name: parameters[:name])
    unless parameters[:teacher_id].blank?
      teacher = Teacher.find(parameters[:teacher_id])

      if teacher.group.blank?
        group.update(teacher: teacher)
      else
        teacher.group.update(teacher: nil)
        group.update(teacher: teacher)
      end
    end

    if group.errors.blank?
      respond_to do |format|
        format.html { redirect_to groups_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = group.errors
      respond_to do |format|
        format.html { redirect_to new_group_path }
        format.json { render json: {erros: group.errors} }
      end
    end
  end

  def edit
    @group = Group.find(params[:id])
    @selection = Teacher.all.collect {|p| [ p.name, p.id ] }
  end

  def update
    parameters = params[:group]
    group = Group.find(params[:id])
    group.update(name: parameters[:name])

    if !parameters[:teacher_id].blank?
      teacher = Teacher.find(parameters[:teacher_id])

      if teacher.group.blank?
        group.update(teacher: teacher)
      else
        teacher.group.update(teacher: nil)
        group.update(teacher: teacher)
      end
    else
      group.update(teacher: nil)
    end

    if group.errors.blank?
      respond_to do |format|
        format.html { redirect_to groups_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = group.errors
      respond_to do |format|
        format.html { redirect_to new_group_path }
        format.json { render json: {errors: group.errors} }
      end
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy

    respond_to do |format|
      format.html { redirect_to groups_path }
      format.json { render json: {success: true} }
    end
  end

  def show
    @group = Group.find(params[:id])

    api_students = []
    @group.students.each do |student|
      api_students << {name: student&.name, surname: student&.name}
    end

    respond_to do |format|
      format.html
      format.json { render json: api_students }
    end
  end
end

app/views/groups/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Edit group</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>


  <%= form_with(model: @group, local: true) do |form| %>
    <p>
      <%= form.label 'Name' %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label 'Teacher' %><br>
      <%= form.select :teacher_id, @selection, { include_blank: true }, :value => @group&.teacher&.name %>
    </p>

    <p>
      <%= form.submit 'Change' %>
    </p>
  <% end %>
</div>

app/views/groups/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<%= link_to 'Add group', new_group_path %>


<div class="container">
  <table class="table table-borderless bg-light">
    <thead>
      <tr class="table-primary">
        <th scope="col">name</th>
        <th scope="col">teacher</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= link_to group.name, group_path(group) %></td>
          <td><%= group&.teacher&.name %> <%= group&.teacher&.surname %></td>
          <td><%= link_to 'Edit', edit_group_path(group) %></td>
          <td><%= link_to 'Remove', group_path(group),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Add new group</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>

  <%= form_with scope: :group, url: groups_path, local: true do |form| %>
    <p>
      <%= form.label 'Name' %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label 'Teacher' %><br>
      <%= form.select :teacher_id, @selection, { include_blank: true } %>
    </p>
    <p>
      <%= form.submit 'Add' %>
    </p>
  <% end %>
</div>

app/views/groups/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <table class="table table-borderless bg-light">
    <thead>
      <tr class="table-primary">
        <th scope="col">name</th>
        <th scope="col">surname</th>
      </tr>
    </thead>
    <tbody>
      <% @group.students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.surname %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>