config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  resources :teachers
  resources :groups
  resources :classrooms
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_one :group
  has_one :classroom

  validates :name, presence: true
  validates :surname, presence: true
  validates :subject, presence: true
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html
      format.json { render json: @teachers }
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def destroy
    teacher = Teacher.find(params[:id])
    teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_path }
      format.json { render json: {success: true} }
    end
  end

  def new
  end

  def update
    parameters = params[:teacher]
    teacher = Teacher.find(params[:id])

    teacher.update(surname: parameters[:surname],
                    name: parameters[:name],
                    subject: parameters[:subject])

    if teacher.errors.blank?
      respond_to do |format|
        format.html { redirect_to teachers_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = teacher.errors
      respond_to do |format|
        format.html { redirect_to edit_teacher_path }
        format.json { render json: {errors: teacher.errors} }
      end
    end
  end

  def create
    parameters = params[:teacher]

    teacher = Teacher.create(surname: parameters[:surname],
                              name: parameters[:name],
                              subject: parameters[:subject])

    if teacher.errors.blank?
      respond_to do |format|
        format.html { redirect_to teachers_path }
        format.json { render json: {success: true} }
      end
    else
      flash[:errors] = teacher.errors
      respond_to do |format|
        format.html { redirect_to new_teacher_path }
        format.json { render json: {errors: teachers.errors} }
      end
    end
  end
end

app/views/teachers/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Edit teacher</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>


  <%= form_with(model: @teacher, local: true) do |form| %>
    <p>
      <%= form.label 'Name' %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label 'Surname' %><br>
      <%= form.text_field :surname %>
    </p>

    <p>
      <%= form.label 'Subject' %><br>
      <%= form.text_field :subject %>
    </p>

    <p>
      <%= form.submit 'Change' %>
    </p>
  <% end %>
</div>

app/views/teachers/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<%= link_to 'Add teacher', new_teacher_path %>


<div class="container">
  <table class="table table-borderless bg-light">
    <thead>
      <tr class="table-primary">
        <th scope="col">name</th>
        <th scope="col">surname</th>
        <th scope="col">subject</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @teachers.each do |teacher| %>
        <tr>
          <td><%= teacher.name %></td>
          <td><%= teacher.surname %></td>
          <td><%= teacher.subject %></td>
          <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
          <td><%= link_to 'Fire', teacher_path(teacher),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/teachers/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'students', students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'groups', groups_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'classrooms', classrooms_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <h1>Add new teacher</h1>

  <% flash[:errors]&.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>

  <%= form_with scope: :teacher, url: teachers_path, local: true do |form| %>
    <p>
      <%= form.label 'Name' %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label 'Surname' %><br>
      <%= form.text_field :surname %>
    </p>

    <p>
      <%= form.label 'Subject' %><br>
      <%= form.text_field :subject %>
    </p>

    <p>
      <%= form.submit 'Add' %>
    </p>
  <% end %>
</div>